# Object oriented programming(oops)
## Class:
    - Bluprint for creating an object
    - Collection of variables and methods

In [2]:
a=[1,2,3]
print(type(a))

<class 'list'>


In [3]:
print(dir(list))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [4]:
print(help(list.append))

Help on method_descriptor:

append(self, object, /)
    Append object to the end of the list.

None


In [5]:
class person:
    age = 21
    def greet(self):
        print("hello")
person.greet

<function __main__.person.greet(self)>

In [6]:
person.age

21

### Object:
   - instance of class

In [7]:
p = person()
p.greet

<bound method person.greet of <__main__.person object at 0x000001D2455E33A0>>

In [8]:
p.greet()

hello


In [9]:
p.age

21

In [12]:
def add():
    c=2+3
    print(c)
add

<function __main__.add()>

In [13]:
add()

5


### Constructors

In [14]:
class apssdc:
    d='python'
    def __init__(self):
        print("I am constructor")
x=apssdc()
x.d

I am constructor


'python'

In [15]:
class apssdc:
    d='python'
    def __init__(self,a,b):
        print("I am constructor")
        print(a,b)
x=apssdc(10,20)
x.d

I am constructor
10 20


'python'

In [17]:
class apssdc:
    def __init__(self,name,number):
        self.name=name
        self.number=number
    def display(self):
        print(self.name)
    def display1(self):
        print(self.number)
x=apssdc("alekhya",9876543210)
x.display()

alekhya


In [18]:
x.display1()

9876543210


## Inheritance

In [24]:
class A: # base class/parent class
    def details(self,name):
        self.name=name
        print(self.name)
class B(A):# derived class/ child class
    def display(self):
        print("derived class")
z=B()
z.display()
z.details("Raju")

derived class
Raju


## Multiple Inheritance
- one class acquires the properties of one or more parent class

In [31]:
class A:
    def display(self):
        print("I am from a class")
class B:
    def display1(self):
        print("I am fro b class")
class C(A,B):
    def display2(self):
  x      print("I am child class")
x=C()

In [32]:
x.display()
x.display1()
x.display2()

I am from a class
I am fro b class
I am child class


## Multi Level Inheritance

In [35]:
class A:
    def display(self):
        print("I am from a class")
class B(A):
    def display1(self):
        print("I am fro b class")
class C(B):
    def display2(self):
        print("I am child class")
x=C()

In [36]:
x.display()
x.display1()
x.display2()

I am from a class
I am fro b class
I am child class


# Data Analysis
- Kaggle website using for dataset

In [1]:
#modules
print(help("modules"))


Please wait a moment while I gather a list of all available modules...



C:\Users\bvnrc\anaconda3\lib\site-packages\IPython\kernel\__init__.py:12: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  warn("The `IPython.kernel` package has been deprecated since IPython 4.0."
C:\Users\bvnrc\anaconda3\lib\pkgutil.py:92: MatplotlibDeprecationWarning: 
The matplotlib.compat module was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  __import__(info.name)
C:\Users\bvnrc\anaconda3\lib\site-packages\nltk\twitter\__init__.py:21: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn(
C:\Users\bvnrc\anaconda3\lib\site-packages\skimage\viewer\utils\__init__.py:1: UserWarning: Recommended matplotlib backend is `Agg` for full skimage.viewer functionality.
  from .core import *
C:\Users\bvnrc\anaconda3\lib\site-packages\qtawesome\iconic_font.py:311: UserWarning: You need t

Cython              brain_responses     marshal             socket
IPython             brain_scipy_signal  math                socketserver
OpenSSL             brain_six           matplotlib          socks
PIL                 brain_ssl           mccabe              sockshandler
PyQt5               brain_subprocess    menuinst            sortedcollections
__future__          brain_threading     mimetypes           sortedcontainers
_abc                brain_typing        mistune             soupsieve
_ast                brain_uuid          mkl                 sphinx
_asyncio            brotli              mkl_fft             sphinxcontrib
_bisect             bs4                 mkl_random          spyder
_blake2             builtins            mmap                spyder_kernels
_bootlocale         bz2                 mmapfile            sqlalchemy
_bz2                cProfile            mmsystem            sqlite3
_cffi_backend       calendar            mock                sre_compile
_c

attr                imagesize           pywintypes          win32print
audioop             imaplib             pywt                win32process
autopep8            imghdr              pyximport           win32profile
autoreload          imp                 qdarkstyle          win32ras
babel               importlib           qtawesome           win32rcparser
backcall            importlib_metadata  qtconsole           win32security
backports           iniconfig           qtpy                win32service
base64              inspect             queue               win32serviceutil
bcrypt              intervaltree        quopri              win32timezone
bdb                 io                  random              win32trace
binascii            ipaddress           rasutil             win32traceutil
binhex              ipykernel           re                  win32transaction
binstar_client      ipykernel_launcher  readline            win32ts
bisect              ipython_genutils    regcheck   

In [2]:
pip list

Package                            Version
---------------------------------- -------------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.10.0
anaconda-project                   0.8.3
Note: you may need to restart the kernel to use updated packages.argh                               0.26.2

argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.2
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0
autopep8                           1.5.4
Babel                              2.8.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.2.0
beautifuls

sortedcontainers                   2.2.2
soupsieve                          2.0.1
Sphinx                             3.2.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.1.5
spyder-kernels                     1.9.4
SQLAlchemy                         1.3.20
statsmodels                        0.12.0
sympy                              1.6.2
tables                             3.6.1
tblib                              1.7.0
terminado                          0.9.1
testpath                           0.4.4
threadpoolctl                      2.1.0
tifffile                           2020.10.1
toml                               0.10.1
toolz                              0.11.1
tornado                            6.0.4
tqdm    

# Numpy

In [3]:
import numpy

In [5]:
pip install numpy

In [6]:
import numpy as np

##### creating an array
- 1-D array

In [7]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [8]:
a=np.array([1,2,3,4,5])

In [9]:
a

array([1, 2, 3, 4, 5])

In [10]:
a.dtype

dtype('int32')

In [11]:
b=np.array(["a"])
b.dtype

dtype('<U1')

In [12]:
c=np.array(["a",9.7,34])

In [18]:
a=np.append(a,[6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
l=[1,2,3]
l.append([5,6])

In [17]:
l

[1, 2, 3, [5, 6]]

In [20]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [21]:
np.arange(1,21.5,5)

array([ 1.,  6., 11., 16., 21.])

In [22]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [23]:
a.itemsize

4

In [24]:
len(a)

8

In [25]:
a.nbytes

32

In [26]:
np.full(10,"apssdc")

array(['apssdc', 'apssdc', 'apssdc', 'apssdc', 'apssdc', 'apssdc',
       'apssdc', 'apssdc', 'apssdc', 'apssdc'], dtype='<U6')

In [27]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [29]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
a=np.array([1,6,7])

In [33]:
a.ndim

1