In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
a.ndim

1

### 2-D array

In [6]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
b.ndim


2

In [9]:
b.nbytes

32

In [10]:
b.itemsize

4

In [11]:
len(b)

2

In [12]:
b.size

8

In [13]:
# 3-D array
c=np.array([[[1,2,3,4],[5,6,7,8]]])
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [14]:
c.ndim

3

In [15]:
c=np.array([[[1,2,3,4],[5,6,7,8]],[[7,8,9,10],[1,2,3,4]]])

In [38]:
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 7,  8,  9, 10],
        [ 1,  2,  3,  4]]])

In [17]:
c.ndim

3

In [18]:
a

array([1, 2, 3, 4])

In [19]:
a[2]

3

In [20]:
a[-1]

4

In [21]:
a[1:]

array([2, 3, 4])

In [22]:
# 2-D array

In [23]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
b[0]

array([1, 2, 3, 4])

In [25]:
b[1]

array([5, 6, 7, 8])

In [26]:
b[0][1]

2

In [28]:
b[0,1]

2

In [30]:
b[:,-2:] 

array([[3, 4],
       [7, 8]])

In [31]:
b[1:,-2:]

array([[7, 8]])

In [32]:
b[0:2,1:1]

array([], shape=(2, 0), dtype=int32)

In [33]:
b[1:,-2:]

array([[7, 8]])

In [34]:
# 3-D array

In [35]:
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 7,  8,  9, 10],
        [ 1,  2,  3,  4]]])

In [39]:
c[0]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 7,  8,  9, 10],
       [ 1,  2,  3,  4]])

In [41]:
c[0,0,3]

4

In [42]:
c[:,:,3:]

array([[[ 4],
        [ 8],
        [10],
        [ 4]]])

In [43]:
c[:,:,-1]

array([[ 4,  8, 10,  4]])

In [44]:
#reshaping the array

In [45]:
a

array([1, 2, 3, 4])

In [46]:
a=np.array([1,2,3,4,5,6,7,8,9,10])

In [47]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
a.shape

(10,)

In [49]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [51]:
a.reshape(5,2,1)

array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]]])

In [53]:
b.reshape(4,2,1)

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]],

       [[7],
        [8]]])

In [54]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
a.reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [58]:
a.reshape(1,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

## concatenation

In [60]:
#1-D array

In [63]:
a1=np.array([1,2,3,4])
a2=np.array([3,4,5,6])
a3=np.array([5,6,7,8])
np.concatenate((a1,a2))

array([1, 2, 3, 4, 3, 4, 5, 6])

In [64]:
#2-D array
b1=np.array([[1,2],[3,4]])
b2=np.array([[4,5],[9,10]])
np.concatenate((b1,b2))

array([[ 1,  2],
       [ 3,  4],
       [ 4,  5],
       [ 9, 10]])

In [67]:
#3-D array
c1=b1.reshape(2,2,1)
c2=b2.reshape(2,2,1)

In [68]:
np.concatenate((c1,c2))

array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 4],
        [ 5]],

       [[ 9],
        [10]]])

In [69]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
np.min(a)

1

In [71]:
np.max(a)

10

In [72]:
np.argmin(a)

0

In [73]:
np.argmax(a)

9

In [74]:
np.mean(a)

5.5

In [75]:
np.average(a)

5.5

In [76]:
np.var(a)

8.25

In [77]:
np.std(a)

2.8722813232690143

In [78]:
np.sum(a)

55

In [80]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [81]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [82]:
np.min(b)

1

In [87]:
np.min(b,axis=1) ## 1 represent row

array([1, 5])

In [88]:
np.min(b,axis=0) ## 0 represent column

array([1, 2, 3, 4])

In [86]:
np.argmax(b,1)

array([3, 3], dtype=int64)

In [94]:
np.max(b[0])

4

In [92]:
np.min(b[1])

5

In [93]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Stacking
- arranging elements in proper order
    - horizantal stacking
    - vertical stacking

In [95]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
np.stack(b)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [97]:
np.hstack(b)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [98]:
np.vstack(b)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [99]:
np.vstack(a)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [100]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [101]:
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [102]:
np.log(b)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154]])

In [103]:
np.log2(b)

array([[0.        , 1.        , 1.5849625 , 2.        ],
       [2.32192809, 2.5849625 , 2.80735492, 3.        ]])

In [104]:
np.log10(b)

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999]])

In [105]:
np.remainder(b,4)

array([[1, 2, 3, 0],
       [1, 2, 3, 0]], dtype=int32)

In [106]:
np.power(b,2)

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [107]:
np.multiply(b,6)

array([[ 6, 12, 18, 24],
       [30, 36, 42, 48]])

In [110]:
[1,2,3,4]*6

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [111]:
np.divide(b,5)

array([[0.2, 0.4, 0.6, 0.8],
       [1. , 1.2, 1.4, 1.6]])

In [115]:
x=np.array([1+2.j,5+6.j])

In [113]:
np.real(x)

array([1., 5.])

In [117]:
np.imag(x)

array([2., 6.])

## ravel and flatten

In [126]:
original=np.array([1,2,3,4])
rav=original.ravel()
rav

array([1, 2, 3, 4])

In [127]:
rav[0]=10

In [128]:
rav

array([10,  2,  3,  4])

In [123]:
original

array([1, 2, 3, 4])

In [125]:
fla=original.flatten()
fla

array([1, 2, 3, 4])

In [129]:
fla[2]=30

In [130]:
fla

array([ 1,  2, 30,  4])

In [131]:
original

array([10,  2,  3,  4])

### Random Methods

In [132]:
np.random.random()
# it returns a value between 0 and 1

0.9634027265457126

In [133]:
np.random.random(10)

array([0.51990234, 0.42699514, 0.29410377, 0.84972266, 0.72187722,
       0.41423249, 0.33343602, 0.18474128, 0.26754468, 0.80107784])

In [136]:
np.random.random((5,2))

array([[0.29203448, 0.70197687],
       [0.22583947, 0.13329065],
       [0.1168336 , 0.08402819],
       [0.81146204, 0.87850259],
       [0.94538604, 0.38100412]])

In [137]:
np.random.rand()
# it is similar to random method

0.007871667542035943

In [142]:
np.random.randint(25) # range

15

In [143]:
np.random.randint(10,20)

18

### Filtering

In [144]:
marks=np.array([55,34,89,90,56])

In [146]:
marks[marks>35]

array([55, 89, 90, 56])

In [147]:
x=np.arange(50,100)

In [148]:
x

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [152]:
x[x%2==0]

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])

In [153]:
x>60

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [157]:
x[(x>60)&(x<90)]

array([61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89])

In [159]:
x[((x>60)&(x<90)&(x%2==0))]

array([62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88])

# Pandas
- analysize and manipulate the data
- import/export the data

- series : 1d array 
    - list,tuple,numpy
    - data types --> float,int,string/object
- dataframe : 2d array  
    - list,tuple,numpy array
    - data types --> float,int,string/object

In [160]:
import pandas as pd

In [161]:
 # pip install pandas

In [164]:
s1=pd.Series([1,2,3,7,9,"a"])

In [165]:
s1

0    1
1    2
2    3
3    7
4    9
5    a
dtype: object

In [167]:
s2=pd.Series((1,2,3))

In [168]:
 s2

0    1
1    2
2    3
dtype: int64

In [169]:
s2.index

RangeIndex(start=0, stop=3, step=1)

In [172]:
s3=pd.Series((1,2,3))

In [173]:
s3

0    1
1    2
2    3
dtype: int64

In [174]:
s3=pd.Series(np.array([1,2,3,4]))

In [175]:
s3

0    1
1    2
2    3
3    4
dtype: int32